@accessToken = 2|FDaMlBCRe5ZfRsVWjrDrvyBkoMcPCQ3SxbU3PgrT2be10965
#### Login

POST  http://127.0.0.1:8000/api/login
Content-Type: application/json

{
    "email":"admin@test.com",
    "password":"admin_password"
}

### Register
POST  http://127.0.0.1:8000/api/register
Content-Type: application/json

{
    "name":"pepe",
    "email":"admin40@test.com",
    "password":"admin_password"
}

#### Logout
POST  http://127.0.0.1:8000/api/logout
Authorization: Bearer {{accessToken}}

#### refresh
POST  http://127.0.0.1:8000/api/refresh
Authorization: Bearer {{accessToken}}


#### Obtener todos las tareas
GET http://localhost:8000/api/tareas

#### Obtener una tarea
GET http://localhost:8000/api/tareas/2

### Crear tarea
POST   http://localhost:8000/api/tareas
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
    "descripcion": "tarea 1",
    "ejecutada": "S"
}


### Actualizar tarea
PUT   http://localhost:8000/api/tareas/2
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
    "descripcion": "tarea 2",
    "ejecutada": "S"
}

### Obtener Tarea por Id

DELETE   http://localhost:8000/api/tareas/2
Content-Type: application/json
Authorization: Bearer {{accessToken}}


